INSERT INTO requirements VALUES('Programming','1','Safety. Do the following:');
INSERT INTO requirements VALUES('Programming','1a','Show your counselor your current, up-to-date Cyber Chip. ');
INSERT INTO requirements VALUES('Programming','1b','Discuss first aid and prevention for the types of injuries or illnesses that could occur during programming activities, including repetitive stress injuries and eyestrain.');
INSERT INTO requirements VALUES('Programming','2','History. Do the following:');
INSERT INTO requirements VALUES('Programming','2a','Give a brief history of programming, including at least three milestones related to the advancement or development of programming.');
INSERT INTO requirements VALUES('Programming','2b','Describe the evolution of programming methods and how they have improved over time.');
INSERT INTO requirements VALUES('Programming','3','General knowledge. Do the following:');
INSERT INTO requirements VALUES('Programming','3a','Create a list of 10 popular programming languages in use today and describe which industry or industries they are primarily used in and why.');
INSERT INTO requirements VALUES('Programming','3b','Describe three different programmed devices you rely on every day.');
INSERT INTO requirements VALUES('Programming','4','Intellectual property. Do the following:');
INSERT INTO requirements VALUES('Programming','4a','Explain how software patents and copyrights protect a programmer.');
INSERT INTO requirements VALUES('Programming','4b','Describe the difference between licensing and owning software.');
INSERT INTO requirements VALUES('Programming','4c','Describe the differences between freeware, open source, and commercial software, and why it is important to respect the terms of use of each.');
INSERT INTO requirements VALUES('Programming','5','Projects. Do the following:');
INSERT INTO requirements VALUES('Programming','5a','With your counselor''s approval, choose a sample program. Then, as a minimum, modify the code or add a function or subprogram to it. Debug and demonstrate the modified program to your counselor.');
INSERT INTO requirements VALUES('Programming','5b','With your counselor''s approval, choose a second programming language and development environment, different from those used for requirement 5a and in a different industry from 5a. Then write, debug, and demonstrate a functioning program to your counselor, using that language and environment.');
INSERT INTO requirements VALUES('Programming','5c','With your counselor''s approval, choose a third programming language and development environment, different from those used for requirements 5a and 5b and in a different industry from 5a or 5b. Then write, debug, and demonstrate a functioning program to your counselor, using that language and environment.');
INSERT INTO requirements VALUES('Programming','5d','Explain how the programs you wrote for requirements 5a, 5b, and 5c process inputs, how they make decisions based on those inputs, and how they provide outputs based on the decision making.');
INSERT INTO requirements VALUES('Programming','6','Careers. Find out about three career opportunities in programming. Pick one and find out the education, training, and experience required. Discuss this with your counselor and explain why this career might be of interest to you.');
